return {
  objetoFisico = require "entidades.Objetos_Mapa.objetoFisico",
  objeto = require "entidades.Objetos_Mapa.objeto",
  textura = require "entidades.Objetos_Mapa.textura",
  texturaFisica = require "entidades.Objetos_Mapa.texturaFisica",
  player = require "entidades.Player.player",
  puerta = require "entidades.Objetos_Mapa.puerta",
  movible = require "entidades.Objetos_Mapa.movible",
  enemigo1 = require "entidades.Enemigos.enemigo1",
  enemigo2 = require "entidades.Enemigos.enemigo2",
  enemigo3 = require "entidades.Enemigos.enemigo3",
  npc = require "entidades.Npcs.npc",
  arma = require "entidades.Objetos.arma",
  municion = require "entidades.Objetos.municion",
  vida = require "entidades.Objetos.vida",
  meteorito = require "entidades.Objetos_Mapa.meteorito",
  meteoritoCreador = require "entidades.Creador.meteoritoCreador",
  zombieCreador = require "entidades.Creador.zombieCreador",
  animacion = require "entidades.Objetos_Mapa.animacion",
  liquido = require "entidades.Objetos_Mapa.liquido"
}