return  {
  accesorios = require "assets.img.Accesorios.accesorios",
  adornos = require "assets.img.Adornos.adornos",
  burbujas = require "assets.img.Adornos.burbujas",
  ventanas = require "assets.img.Adornos.ventanas",
  armas = require "assets.img.Armas.armas",
  balas = require "assets.img.Armas.balas",
  capa2 = require "assets.img.Capa_2.capa_2",
  capa3 = require "assets.img.Capa_3.capa_3",
  baba = require "assets.img.Enemigos.baba",
  municion = require "assets.img.Items.municion",
  vida = require "assets.img.Items.vida",
  jugador = require "assets.img.Jugadores.jugadores",
  meteorito = require "assets.img.Meteorito.meteorito",
  arbol = require "assets.img.Objetos.arbol",
  helado = require "assets.img.Objetos.helado",
  objetos = require "assets.img.Objetos.objetos",
  sundae = require "assets.img.Objetos.sundae",
  texturas = require "assets.img.Texturas.texturas",
  ui = require "assets.img.UI.ui" 
}