return {
  version = "1.2",
  luaversion = "5.1",
  tiledversion = "1.3.0",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 200,
  height = 50,
  tilewidth = 32,
  tileheight = 32,
  nextlayerid = 4,
  nextobjectid = 77,
  properties = {},
  tilesets = {},
  layers = {
    {
      type = "objectgroup",
      id = 3,
      name = "Borrador",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 7,
          name = "Personaje",
          type = "",
          shape = "point",
          x = 142.667,
          y = 1118.67,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 27,
          name = "Baba",
          type = "",
          shape = "point",
          x = 457.333,
          y = 1126,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 35,
          name = "Gelatina",
          type = "",
          shape = "polygon",
          x = 14,
          y = 1192,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = -11.3333, y = 0.666667 },
            { x = 1836, y = -8 },
            { x = 1757, y = 146 },
            { x = 1737.93, y = 218 },
            { x = 1704.63, y = 402 },
            { x = -12.6093, y = 407.333 }
          },
          properties = {}
        },
        {
          id = 36,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2,
          y = 930,
          width = 228,
          height = 260,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 40,
          name = "Gelatina",
          type = "",
          shape = "polygon",
          x = 1986.67,
          y = 1596,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 25.3333, y = -106.667 },
            { x = 75, y = -200 },
            { x = 400.667, y = -201.333 },
            { x = 443, y = -247.667 },
            { x = 508, y = -266.333 },
            { x = 510.667, y = -477.333 },
            { x = 1201.33, y = -468.138 },
            { x = 1329.27, y = -302.815 },
            { x = 1932.86, y = -302.602 },
            { x = 1941.34, y = -562.474 },
            { x = 3562.67, y = -892 },
            { x = 3699.33, y = -891.987 },
            { x = 3767.33, y = -833.981 },
            { x = 3863.19, y = -887.543 },
            { x = 4409.79, y = -891.92 },
            { x = 4408.98, y = 7.52266 }
          },
          properties = {}
        },
        {
          id = 44,
          name = "",
          type = "",
          shape = "rectangle",
          x = 234,
          y = 1014.67,
          width = 322.667,
          height = 173.334,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 45,
          name = "",
          type = "",
          shape = "rectangle",
          x = 556.667,
          y = 928.667,
          width = 228,
          height = 260,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 46,
          name = "",
          type = "",
          shape = "rectangle",
          x = 786,
          y = 758,
          width = 288,
          height = 429.333,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 47,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1076,
          y = 1010.67,
          width = 468,
          height = 173.334,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 48,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2152.33,
          y = 1132,
          width = 228,
          height = 260,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 49,
          name = "",
          type = "",
          shape = "polygon",
          x = 2573.33,
          y = 1114.67,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 2.66667, y = -77.3333 },
            { x = 40, y = -41.3333 },
            { x = 70.6667, y = -81.3333 },
            { x = 96, y = -40 },
            { x = 168, y = -86.6667 },
            { x = 213.333, y = -38.6667 },
            { x = 236, y = 2.66667 }
          },
          properties = {}
        },
        {
          id = 51,
          name = "",
          type = "",
          shape = "polygon",
          x = 2976,
          y = 1120,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = -552, y = -224 },
            { x = -488, y = -368 },
            { x = 174, y = -82 },
            { x = 108, y = -60 },
            { x = 136, y = -24 },
            { x = 80, y = 2 }
          },
          properties = {}
        },
        {
          id = 52,
          name = "",
          type = "",
          shape = "polygon",
          x = 3338,
          y = 1290,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = -8, y = -168 },
            { x = 30, y = -130 },
            { x = 70, y = -166 },
            { x = 96, y = -122 },
            { x = 146, y = -160 },
            { x = 150, y = -6 }
          },
          properties = {}
        },
        {
          id = 53,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3624,
          y = 1028,
          width = 228,
          height = 260,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 54,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3946.43,
          y = 762.388,
          width = 228,
          height = 260,
          rotation = -11.1036,
          visible = true,
          properties = {}
        },
        {
          id = 55,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4126.67,
          y = 474.907,
          width = 228,
          height = 505.137,
          rotation = -11.1036,
          visible = true,
          properties = {}
        },
        {
          id = 56,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4418.02,
          y = 769.406,
          width = 465.708,
          height = 158.864,
          rotation = -11.1036,
          visible = true,
          properties = {}
        },
        {
          id = 58,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4823.43,
          y = 415.993,
          width = 228,
          height = 419.242,
          rotation = -11.1036,
          visible = true,
          properties = {}
        },
        {
          id = 59,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5073.67,
          y = 485.185,
          width = 228,
          height = 300.902,
          rotation = -11.1036,
          visible = true,
          properties = {}
        },
        {
          id = 60,
          name = "Baba",
          type = "",
          shape = "point",
          x = 1184,
          y = 1138.67,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 61,
          name = "Baba",
          type = "",
          shape = "point",
          x = 878,
          y = 1139.33,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 62,
          name = "Baba",
          type = "",
          shape = "point",
          x = 690.667,
          y = 1151.33,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 63,
          name = "Baba",
          type = "",
          shape = "point",
          x = 1481,
          y = 1140,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 64,
          name = "Baba",
          type = "",
          shape = "point",
          x = 1773,
          y = 1127,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 65,
          name = "Baba",
          type = "",
          shape = "point",
          x = 2116,
          y = 1363,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 66,
          name = "Baba",
          type = "",
          shape = "point",
          x = 2332,
          y = 1359,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 67,
          name = "Baba",
          type = "",
          shape = "point",
          x = 3598,
          y = 1265,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 68,
          name = "Baba",
          type = "",
          shape = "point",
          x = 3531,
          y = 1267,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 69,
          name = "Baba",
          type = "",
          shape = "point",
          x = 3873,
          y = 1260,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 70,
          name = "Baba",
          type = "",
          shape = "point",
          x = 5609,
          y = 674,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 71,
          name = "Baba",
          type = "",
          shape = "point",
          x = 5283,
          y = 735,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 72,
          name = "Baba",
          type = "",
          shape = "point",
          x = 5031,
          y = 775,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 73,
          name = "Baba",
          type = "",
          shape = "point",
          x = 4846,
          y = 834,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 74,
          name = "Baba",
          type = "",
          shape = "point",
          x = 4512,
          y = 876,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 75,
          name = "Baba",
          type = "",
          shape = "point",
          x = 4250,
          y = 928,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 76,
          name = "Baba",
          type = "",
          shape = "point",
          x = 6114,
          y = 663,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
