return {
  version = "1.2",
  luaversion = "5.1",
  tiledversion = "1.3.0",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 125,
  height = 40,
  tilewidth = 32,
  tileheight = 32,
  nextlayerid = 4,
  nextobjectid = 34,
  properties = {},
  tilesets = {},
  layers = {
    {
      type = "objectgroup",
      id = 3,
      name = "Borrador",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 7,
          name = "Personaje",
          type = "",
          shape = "point",
          x = 98,
          y = 997.333,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 22,
          name = "Gelatina",
          type = "",
          shape = "polygon",
          x = 2,
          y = 1055.93,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = -1.5, y = -21 },
            { x = 738.67, y = -26.4494 },
            { x = 1024.16, y = -26.032 },
            { x = 1006.05, y = 15.1682 },
            { x = 1034.47, y = 40.5634 },
            { x = 1022.6, y = 108.168 },
            { x = 1059.83, y = 223.902 },
            { x = -1, y = 224.567 }
          },
          properties = {}
        },
        {
          id = 23,
          name = "Gelatina",
          type = "",
          shape = "polygon",
          x = 1321.21,
          y = 1278.79,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = -18.0513, y = -16.2262 },
            { x = 1.70882, y = -31.028 },
            { x = 303.03, y = -33.3333 },
            { x = 306.061, y = -269.697 },
            { x = 833.333, y = -266.667 },
            { x = 1874.73, y = -630.242 },
            { x = 2676.46, y = -636.724 },
            { x = 2672.12, y = -5.09515 }
          },
          properties = {}
        },
        {
          id = 24,
          name = "Baba",
          type = "",
          shape = "point",
          x = 672,
          y = 978,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 25,
          name = "Baba",
          type = "",
          shape = "point",
          x = 856,
          y = 978,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 27,
          name = "Baba",
          type = "",
          shape = "point",
          x = 436,
          y = 978,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 28,
          name = "Baba",
          type = "",
          shape = "point",
          x = 1559.33,
          y = 1208.67,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 29,
          name = "Baba",
          type = "",
          shape = "point",
          x = 2084,
          y = 982.667,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 30,
          name = "Baba",
          type = "",
          shape = "point",
          x = 3234,
          y = 632,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 31,
          name = "Baba",
          type = "",
          shape = "point",
          x = 2428,
          y = 856,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 32,
          name = "Baba",
          type = "",
          shape = "point",
          x = 1788,
          y = 972,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 33,
          name = "Baba",
          type = "",
          shape = "point",
          x = 2706,
          y = 758,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
