return {
  version = "1.2",
  luaversion = "5.1",
  tiledversion = "1.3.0",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 200,
  height = 50,
  tilewidth = 32,
  tileheight = 32,
  nextlayerid = 4,
  nextobjectid = 87,
  properties = {},
  tilesets = {},
  layers = {
    {
      type = "objectgroup",
      id = 3,
      name = "Borrador",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 7,
          name = "Personaje",
          type = "",
          shape = "point",
          x = 142.667,
          y = 1118.67,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 27,
          name = "Baba",
          type = "",
          shape = "point",
          x = 457.333,
          y = 1126,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 35,
          name = "Gelatina",
          type = "",
          shape = "polygon",
          x = 14,
          y = 1192,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = -14.2083, y = -2.33333 },
            { x = 1836, y = -8 },
            { x = 1757, y = 146 },
            { x = 1737.93, y = 218 },
            { x = 1704.63, y = 407.667 },
            { x = -14.2343, y = 408.333 }
          },
          properties = {}
        },
        {
          id = 36,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2,
          y = 930,
          width = 228,
          height = 260,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 40,
          name = "Gelatina",
          type = "",
          shape = "polygon",
          x = 1987.67,
          y = 1596,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 74.6667, y = 3.5 },
            { x = 78.3333, y = -203.333 },
            { x = 509.5, y = -203.083 },
            { x = 507.991, y = 3.31231 }
          },
          properties = {}
        },
        {
          id = 44,
          name = "",
          type = "",
          shape = "rectangle",
          x = 234,
          y = 1014.67,
          width = 322.667,
          height = 173.334,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 45,
          name = "",
          type = "",
          shape = "rectangle",
          x = 556.667,
          y = 928.667,
          width = 228,
          height = 259,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 46,
          name = "",
          type = "",
          shape = "rectangle",
          x = 786,
          y = 758,
          width = 288,
          height = 429.333,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 47,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1076,
          y = 1010.67,
          width = 468,
          height = 175.334,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 48,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2152.33,
          y = 1132,
          width = 228,
          height = 260,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 49,
          name = "",
          type = "",
          shape = "polygon",
          x = 2573.33,
          y = 1114.67,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 2.66667, y = -77.3333 },
            { x = 40, y = -41.3333 },
            { x = 70.6667, y = -81.3333 },
            { x = 96, y = -40 },
            { x = 168, y = -86.6667 },
            { x = 213.333, y = -38.6667 },
            { x = 236, y = 2.66667 }
          },
          properties = {}
        },
        {
          id = 51,
          name = "",
          type = "",
          shape = "polygon",
          x = 2976,
          y = 1120,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = -552, y = -224 },
            { x = -488, y = -368 },
            { x = 174, y = -82 },
            { x = 108, y = -60 },
            { x = 136, y = -24 },
            { x = 80, y = 2 }
          },
          properties = {}
        },
        {
          id = 52,
          name = "",
          type = "",
          shape = "polygon",
          x = 3338,
          y = 1290,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = -8, y = -168 },
            { x = 30, y = -130 },
            { x = 70, y = -166 },
            { x = 96, y = -122 },
            { x = 146, y = -160 },
            { x = 149.333, y = -0.333333 }
          },
          properties = {}
        },
        {
          id = 53,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3624,
          y = 1028,
          width = 228,
          height = 260,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 54,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3946.43,
          y = 762.388,
          width = 228,
          height = 260,
          rotation = -11.1036,
          visible = true,
          properties = {}
        },
        {
          id = 55,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4126.67,
          y = 474.907,
          width = 228,
          height = 505.137,
          rotation = -11.1036,
          visible = true,
          properties = {}
        },
        {
          id = 56,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4418.02,
          y = 769.406,
          width = 465.708,
          height = 158.864,
          rotation = -11.1036,
          visible = true,
          properties = {}
        },
        {
          id = 58,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4823.43,
          y = 415.993,
          width = 228,
          height = 419.242,
          rotation = -11.1036,
          visible = true,
          properties = {}
        },
        {
          id = 59,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5073.67,
          y = 485.185,
          width = 228,
          height = 300.902,
          rotation = -11.1036,
          visible = true,
          properties = {}
        },
        {
          id = 60,
          name = "Baba",
          type = "",
          shape = "point",
          x = 1184,
          y = 1138.67,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 64,
          name = "Baba",
          type = "",
          shape = "point",
          x = 1689,
          y = 1143,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 66,
          name = "Baba",
          type = "",
          shape = "point",
          x = 2332,
          y = 1359,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 68,
          name = "Baba",
          type = "",
          shape = "point",
          x = 3531,
          y = 1267,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 69,
          name = "Baba",
          type = "",
          shape = "point",
          x = 3873,
          y = 1260,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 70,
          name = "Baba",
          type = "",
          shape = "point",
          x = 5609,
          y = 674,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 73,
          name = "Baba",
          type = "",
          shape = "point",
          x = 4846,
          y = 834,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 75,
          name = "Baba",
          type = "",
          shape = "point",
          x = 4250,
          y = 928,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 76,
          name = "Baba",
          type = "",
          shape = "point",
          x = 6114,
          y = 663,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 77,
          name = "Baba",
          type = "",
          shape = "point",
          x = 2830.67,
          y = 1085.33,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 79,
          name = "Gelatina",
          type = "",
          shape = "polygon",
          x = 3950,
          y = 1070,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 15, y = -44.5 },
            { x = 1584, y = -368 },
            { x = 1734, y = -366 },
            { x = 1796, y = -318 },
            { x = 1904, y = -364 },
            { x = 2450, y = -362 },
            { x = 2452, y = 225.333 },
            { x = -34.5563, y = 223.058 }
          },
          properties = {}
        },
        {
          id = 80,
          name = "Gelatina",
          type = "",
          shape = "polygon",
          x = 2494.67,
          y = 1596,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 4 },
            { x = 5.33333, y = -482 },
            { x = 774.667, y = -470.667 },
            { x = 820, y = -305.333 },
            { x = 1421.33, y = -308.667 },
            { x = 1420.85, y = 4.54545 }
          },
          properties = {}
        },
        {
          id = 84,
          name = "Gelatina",
          type = "",
          shape = "polygon",
          x = 2388,
          y = 1395.33,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 31.5, y = -3.41667 },
            { x = 42, y = -46 },
            { x = 109.417, y = -66.8333 },
            { x = 109.167, y = -2.25 }
          },
          properties = {}
        },
        {
          id = 85,
          name = "Gelatina",
          type = "",
          shape = "polygon",
          x = 2065.5,
          y = 1394,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0.515625, y = -1.33984 },
            { x = -50.388, y = -1.27239 },
            { x = -53, y = 97 },
            { x = -77, y = 204.5 },
            { x = -3, y = 204.5 }
          },
          properties = {}
        },
        {
          id = 86,
          name = "Gelatina",
          type = "",
          shape = "polygon",
          x = 3917.33,
          y = 1290.67,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = -1.25, y = 0.25 },
            { x = -2.66667, y = 308 },
            { x = 2482.67, y = 306.667 },
            { x = 2484, y = 4 }
          },
          properties = {}
        }
      }
    }
  }
}
